name: OCR → GeoJSON → Prefill

on:
  workflow_dispatch:
    inputs:
      image:
        description: "Image path or public URL"
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Install Tesseract
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Process image
        run: |
          python src/main.py "${{ github.event.inputs.image }}"
